spring.application.name=encurtaUrl
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}

spring.cassandra.contact-points=${CASSANDRA_POINT}
spring.cassandra.port=${CASSANDRA_PORT}
spring.cassandra.keyspace-name=${CASSANDRA_KEYSPACE}
spring.cassandra.local-datacenter=${CASSANDRA_DATACENTER}

hashids.length=${HASHID_LENGTH}
hashids.salt=${HASHID_SALT}